// LOCALHOST Adventures RESTs

### LOCAL Get api-docs
GET http://localhost:8080/api-docs

// ***** FISH LINKS ******

### Get All Fish
GET  http://localhost:8080/fish

### Get Single Fish by ID -- NOTE: ID must be updated
GET  http://localhost:8080/fish/65341443b71a4c3b78b9e462

### Create new Fish
POST http://localhost:8080/fish HTTP/1.1
content-type: application/json

{
  "type": "Smallmouth Bass",
  "length": 19,
  "weight": 61,
  "date": "10/20/2021",
  "location": "Coeur d'Alene Lake"
}

### Update Fish by ID -- NOTE: ID must be updated
PUT http://localhost:8080/fish/65329383b7549601462ea266 HTTP/1.1
content-type: application/json

{
  "type": "Smallmouth Bass",
  "length": 14.5,
  "weight": 20,
  "date": "07/15/2021",
  "location": "Coeur d'Alene Lake"
}

### Delete Fish by ID -- NOTE: ID must be updated
DELETE  http://localhost:8080/fish/65329383b7549601462ea26ac

// ***** HIKE LINKS *****

### Get All Hikes
GET  http://localhost:8080/hikes

### Get Single Hike by ID -- NOTE: ID must be updated
GET  http://localhost:8080/hikes/652b360485dfe67a099d1b15

### Create new Hike
POST http://localhost:8080/hikes HTTP/1.1
content-type: application/json

{
  "hikeName": "Harrison Peak",
  "location": "Kaniksu National Forest",
  "type": "Out & Back",
  "miles": 4.6,
  "elevationStart": 4674,
  "elevationEnd": 6111,
  "elevationGain": 1437
}

### Update Hike by ID -- NOTE: ID must be updated
PUT http://localhost:8080/hikes/653422e2a86d42c7797ac32e HTTP/1.1
content-type: application/json

{
  "hikeName": "Harrison Peak",
  "location": "Kaniksu National Forest",
  "type": "Out & Back",
  "miles": 5,
  "elevationStart": 4674,
  "elevationEnd": 7292,
  "elevationGain": 2618
}

### Delete Hike by ID -- NOTE: ID must be updated
DELETE  http://localhost:8080/hikes/653422e2a86d42c7797ac32e

// RENDER Adventures RESTs

### RENDER Get api-docs
GET https://kiyoos-adventures.onrender.com/api-docs

// ***** FISH LINKS ******

### Get All Fish
GET  https://kiyoos-adventures.onrender.com/fish

### Get Single Fish by ID -- NOTE: ID must be updated
GET  https://kiyoos-adventures.onrender.com/fish/65341443b71a4c3b78b9e462

### Create new Fish
POST https://kiyoos-adventures.onrender.com/fish HTTP/1.1
content-type: application/json

{
  "type": "Smallmouth Bass",
  "length": 19,
  "weight": 61,
  "date": "10/20/2021",
  "location": "Coeur d'Alene Lake"
}

### Update Fish by ID -- NOTE: ID must be updated
PUT https://kiyoos-adventures.onrender.com/fish/65329383b7549601462ea266 HTTP/1.1
content-type: application/json

{
  "type": "Smallmouth Bass",
  "length": 14.5,
  "weight": 20,
  "date": "07/15/2021",
  "location": "Coeur d'Alene Lake"
}

### Delete Fish by ID -- NOTE: ID must be updated
DELETE  https://kiyoos-adventures.onrender.com/fish/65329383b7549601462ea26ac

// ***** HIKE LINKS *****

### Get All Hikes
GET  https://kiyoos-adventures.onrender.com/hikes

### Get Single Hike by ID -- NOTE: ID must be updated
GET  https://kiyoos-adventures.onrender.com/hikes/6529f7c1b9c8f31137139389

### Create new Hike
POST https://kiyoos-adventures.onrender.com/hikes HTTP/1.1
content-type: application/json

{
  "hikeName": "Harrison Peak",
  "location": "Kaniksu National Forest",
  "type": "Out & Back",
  "miles": 4.6,
  "elevationStart": 4674,
  "elevationEnd": 6111,
  "elevationGain": 1437
}

### Update Hike by ID -- NOTE: ID must be updated
PUT https://kiyoos-adventures.onrender.com/hikes/652b31b4f2b97e3a5fd74501 HTTP/1.1
content-type: application/json

{
  "hikeName": "Harrison Peak",
  "location": "Kaniksu National Forest",
  "type": "Out & Back",
  "miles": 5,
  "elevationStart": 4674,
  "elevationEnd": 7292,
  "elevationGain": 2618
}

### Delete Hike by ID -- NOTE: ID must be updated
DELETE  https://kiyoos-adventures.onrender.com/hikes/652b31b4f2b97e3a5fd74501